#!/usr/bin/python3

# Always run this script relative to current path (eg: `. gadd`). Or else
# `cd` will not actually change directory!

cd $HOME/pnl/github/dot-files/

git checkout T480 >/dev/null

cd $HOME/pnl/github/dot-files/linux/T480/

cp -r                       \
$HOME/.config/i3            \
$HOME/.config/dunst         \
$HOME/.config/compton       \
$HOME/.config/gsimplecal    \
$HOME/pnl/github/dot-files/linux/T480/.config/

cp -r               \
$HOME/.gitconfig    \
$HOME/.bash         \
$HOME/.inputrc      \
$HOME/.Xresources   \
$HOME/.scripts/     \
$HOME/.alias        \
$HOME/.vimrc        \
$HOME/.profile      \
$HOME/.bashrc       \
$HOME/.fonts        \
$HOME/pnl/github/dot-files/linux/T480/

git status
