#!/bin/bash

echo `date`>downspeed
for((i=0;i<10;i++));do
    (speedtest --version >/dev/null && speedtest --no-upload |grep ^Download >>$HOME/downspeed) || echo "Error, check speedtest-cli"
done
echo `date`>upspeed
for((i=0;i<10;i++));do
    speedtest --version >/dev/null && speedtest --no-download |grep ^Upload >>$HOME/upspeed
done
