#!/bin/sh

# Build and move cscope and ctags database to $HOME/.cstags_dir/

# Always use `set nocscoperelative` in vim as this script changes path of cscope
# database and absolute path is needed.
#
# Usage:
#
#    `csb ~/esp/esp-idf/`    or    `csb` (build from current directory)
#
# This will create a cscope database for esp-idf and place it in
# `$HOME/.cstags_dir/`.

mkdir -p $HOME/.cstags_dir
if [ $1 ]; then
    cd $1
fi
target_dir="`basename $PWD`"
cwd=$PWD
mkdir -p $HOME/.cstags_dir/$target_dir
cd $HOME/.cstags_dir/$target_dir
find $cwd -name '*.c' -o -name '*.h' >cscope.files
cscope -bi cscope.files
ctags -R $cwd
